In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
drinks = pd.read_csv("http://bit.ly/drinksbycountry")
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [8]:
# let's find the beer_servings in Turkey

drinks[drinks["country"] == "Turkey"]["beer_servings"].values[0]

51

In [10]:
drinks.head(3)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa

In [9]:
drinks.columns

Index(['country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

In [11]:
drinks.index

RangeIndex(start=0, stop=193, step=1)

In [13]:
#drinks = drinks.set_index("country")
drinks.set_index("country", inplace=True)

In [14]:
drinks.head()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa

In [15]:
drinks.columns

Index(['beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

In [16]:
drinks.index

Index(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua & Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria',
       ...
       'Tanzania', 'USA', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela',
       'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='object', name='country', length=193)

In [ ]:
"""
loc -> location
iloc -> integer location
"""

''

In [18]:
drinks.loc["Turkey","beer_servings"]

51

In [19]:
drinks.loc["Greece", "beer_servings"]

133

In [20]:
drinks.loc[["Turkey", "Greece"], "beer_servings"]

country
Turkey     51
Greece    133
Name: beer_servings, dtype: int64

In [21]:
drinks.loc[["Turkey", "Greece"], ["beer_servings", "wine_servings"]]

         beer_servings  wine_servings
country
Turkey              51              7
Greece             133            218

In [22]:
drinks.head()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa

In [24]:
drinks.loc["Albania", "wine_servings"] = 55

In [25]:
drinks.head()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,55,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa

In [26]:
drinks.loc["Argentina":"Brazil", "beer_servings":"wine_servings"]

                    beer_servings  spirit_servings  wine_servings
country
Argentina                     193               25            221
Armenia                        21              179             11
Australia                     261               72            212
Austria                       279               75            191
Azerbaijan                     21               46              5
Bahamas                       122              176             51
Bahrain                        42               63              7
Bangladesh                      0                0              0
Barbados                      143              173             36
Belarus                       142              373             42
Belgium                       295               84            212
Belize                        263              114              8
Benin                          34                4             13
Bhutan                         23                0              0
Bolivia                       167               41              8
Bosnia-Herzegovina             76              173              8
Botswana                      173               35             35
Brazil                        245              145             16

In [27]:
drinks.loc["Argentina":"Bahamas", :]

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Argentina,193,25,221,8.3,South America
Armenia,21,179,11,3.8,Europe
Australia,261,72,212,10.4,Oceania
Austria,279,75,191,9.7,Europe
Azerbaijan,21,46,5,1.3,Europe
Bahamas,122,176,51,6.3,North America

In [28]:
drinks.head()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,55,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa

In [29]:
drinks.loc["Albania", "wine_servings"]

55

In [30]:
drinks.iloc[1, 2]

55

In [31]:
drinks.iloc[[0, 2], [0, 2]]

             beer_servings  wine_servings
country
Afghanistan              0              0
Algeria                 25             14

In [32]:
drinks.iloc[:3, :2]

             beer_servings  spirit_servings
country
Afghanistan              0                0
Albania                 89              132
Algeria                 25                0

In [33]:
drinks.head()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,55,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa

In [34]:
drinks.reset_index(inplace=True)
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,55,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [35]:
drinks.columns

Index(['country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

In [42]:
drinks.loc[176, :]

country                         Turkey
beer_servings                       51
spirit_servings                     22
wine_servings                        7
total_litres_of_pure_alcohol       1.4
continent                         Asia
Name: 176, dtype: object

In [43]:
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,55,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [49]:
# first 3 rows and 4 columns with loc
drinks.loc[:2 , :"wine_servings"]

       country  beer_servings  spirit_servings  wine_servings
0  Afghanistan              0                0              0
1      Albania             89              132             55
2      Algeria             25                0             14

In [51]:
# first 3 rows and 4 columns with iloc
drinks.iloc[:3 , :4]

       country  beer_servings  spirit_servings  wine_servings
0  Afghanistan              0                0              0
1      Albania             89              132             55
2      Algeria             25                0             14

In [52]:
ufos = pd.read_csv("http://bit.ly/uforeports")
ufos.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [53]:
ufos["City"].value_counts()

City
Seattle          187
New York City    161
Phoenix          137
Houston          108
Las Vegas        105
                ...
Lake Sonoma        1
Von Ormy           1
Grosse Pointe      1
Grosse Point       1
Ybor               1
Name: count, Length: 6475, dtype: int64

In [55]:
ufos.groupby("City").size().sort_values(ascending=False)

City
Seattle                187
New York City          161
Phoenix                137
Houston                108
Las Vegas              105
                      ...
Indian Orchard           1
Indian Lake              1
Indian Heights           1
Indian Falls             1
south of the border      1
Length: 6475, dtype: int64

In [56]:
ufos.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [ ]:
ufos.groupby(["City", "Shape Reported"]).size() # multi-index

City                                 Shape Reported
Abbeville                            DISK              1
Aberdeen                             CIRCLE            1
                                     CYLINDER          1
                                     DISK              1
                                     FIREBALL          2
                                                      ..
none                                 SPHERE            1
not shure                            CIRCLE            1
observer enroute on MN hwy 61 north  SPHERE            1
on plane wing                        DISK              1
south of the border                  DISK              1
Length: 11593, dtype: int64

In [58]:
ufos.groupby(["City", "Shape Reported"]).size().index

MultiIndex([(                          'Abbeville',     'DISK'),
            (                           'Aberdeen',   'CIRCLE'),
            (                           'Aberdeen', 'CYLINDER'),
            (                           'Aberdeen',     'DISK'),
            (                           'Aberdeen', 'FIREBALL'),
            (                           'Aberdeen', 'TRIANGLE'),
            (                           'Aberdeen',  'VARIOUS'),
            (                            'Abilene',     'DISK'),
            (                            'Abilene',   'SPHERE'),
            (                            'Abilene', 'TRIANGLE'),
            ...
            (                            'no data',     'OVAL'),
            (                            'no data', 'TEARDROP'),
            (                            'no data', 'TRIANGLE'),
            (                               'none',   'CIRCLE'),
            (                               'none',     'DISK'),
            (                               'none',   'SPHERE'),
            (                          'not shure',   'CIRCLE'),
            ('observer enroute on MN hwy 61 north',   'SPHERE'),
            (                      'on plane wing',     'DISK'),
            (                'south of the border',     'DISK')],
           names=['City', 'Shape Reported'], length=11593)

In [60]:
ufos.groupby(["City", "Shape Reported"]).size().index[0]

('Abbeville', 'DISK')

In [61]:
ufos.groupby(["City", "Shape Reported"]).size().index[0][1]

'DISK'

In [62]:
ufos.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [ ]:
ufos.isnull()

        City  Colors Reported  Shape Reported  State   Time
0      False             True           False  False  False
1      False             True           False  False  False
2      False             True           False  False  False
3      False             True           False  False  False
4      False             True           False  False  False
...      ...              ...             ...    ...    ...
18236  False             True           False  False  False
18237  False             True           False  False  False
18238  False             True            True  False  False
18239  False            False           False  False  False
18240  False             True           False  False  False

[18241 rows x 5 columns]

In [65]:
ufos.shape

(18241, 5)

In [64]:
ufos.isnull().sum()

City                  26
Colors Reported    15359
Shape Reported      2644
State                  0
Time                   0
dtype: int64