In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
obj = pd.Series([10, 7, 5, 12])
obj

0    10
1     7
2     5
3    12
dtype: int64

In [6]:
obj.values # attributes

array([10,  7,  5, 12])

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj = pd.Series([10, 7, 5, 12], index=["a", "b", "c", "d"])
obj

a    10
b     7
c     5
d    12
dtype: int64

In [8]:
obj.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [9]:
obj["b"]

7

In [10]:
obj[7]

/var/folders/fn/2l89qd8n053f84k8b5q1wknm0000gn/T/ipykernel_40234/2068092161.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[7]

IndexError: index 7 is out of bounds for axis 0 with size 4

In [11]:
obj

a    10
b     7
c     5
d    12
dtype: int64

In [12]:
"b" in obj

True

In [ ]:
7 in obj # faster

False

In [ ]:
7 in obj.values # slower

True

In [15]:
obj

a    10
b     7
c     5
d    12
dtype: int64

In [20]:
obj[["a", "c"]]

a    10
c     5
dtype: int64

In [21]:
obj

a    10
b     7
c     5
d    12
dtype: int64

In [22]:
obj * 2

a    20
b    14
c    10
d    24
dtype: int64

In [23]:
obj + 4

a    14
b    11
c     9
d    16
dtype: int64

In [24]:
obj

a    10
b     7
c     5
d    12
dtype: int64

In [25]:
obj < 7

a    False
b    False
c     True
d    False
dtype: bool

In [26]:
sdata = {"Istanbul": 18000000, "Izmir": 4500000,
         "Bursa": 1800000, "Ankara": 5500000}

obj3 = pd.Series(sdata)
obj3

Istanbul    18000000
Izmir        4500000
Bursa        1800000
Ankara       5500000
dtype: int64

In [27]:
sdata2 = {"Istanbul": 20000000,
         "Bursa": 1800000, "Ankara": 6000000, "Izmir": 5500000,}

obj4 = pd.Series(sdata2)
obj4

Istanbul    20000000
Bursa        1800000
Ankara       6000000
Izmir        5500000
dtype: int64

In [28]:
(obj3 + obj4) / 2

Ankara       5750000.0
Bursa        1800000.0
Istanbul    19000000.0
Izmir        5000000.0
dtype: float64

In [29]:
d = {
    "Name": ["John", "Alice", "Jack", "Rose", "Alex", "David"],
    "Age": [32, 23, 21, 35, 45, 48],
    "City": ["Istanbul", "Paris", "London", "Madrid", "Sao Paulo", "Miami"]
}

data = pd.DataFrame(d)
data

    Name  Age       City
0   John   32   Istanbul
1  Alice   23      Paris
2   Jack   21     London
3   Rose   35     Madrid
4   Alex   45  Sao Paulo
5  David   48      Miami

In [30]:
type(data)

pandas.core.frame.DataFrame

In [31]:
data.shape

(6, 3)

In [32]:
data.dtypes # data type

Name    object
Age      int64
City    object
dtype: object

In [33]:
data

    Name  Age       City
0   John   32   Istanbul
1  Alice   23      Paris
2   Jack   21     London
3   Rose   35     Madrid
4   Alex   45  Sao Paulo
5  David   48      Miami

In [34]:
data.head() # displays first 5 rows

    Name  Age       City
0   John   32   Istanbul
1  Alice   23      Paris
2   Jack   21     London
3   Rose   35     Madrid
4   Alex   45  Sao Paulo

In [35]:
data.tail() # displays last 5 rows

    Name  Age       City
1  Alice   23      Paris
2   Jack   21     London
3   Rose   35     Madrid
4   Alex   45  Sao Paulo
5  David   48      Miami

In [38]:
data.head(2)

    Name  Age      City
0   John   32  Istanbul
1  Alice   23     Paris

In [39]:
data

    Name  Age       City
0   John   32   Istanbul
1  Alice   23      Paris
2   Jack   21     London
3   Rose   35     Madrid
4   Alex   45  Sao Paulo
5  David   48      Miami

In [40]:
data.head(2)

    Name  Age      City
0   John   32  Istanbul
1  Alice   23     Paris

In [41]:
data[:2]

    Name  Age      City
0   John   32  Istanbul
1  Alice   23     Paris

In [ ]:
data["Age"] # a series

0    32
1    23
2    21
3    35
4    45
5    48
Name: Age, dtype: int64

In [43]:
data["Name"]

0     John
1    Alice
2     Jack
3     Rose
4     Alex
5    David
Name: Name, dtype: object

In [ ]:
data[["Name", "Age"]] # dataFrame

    Name  Age
0   John   32
1  Alice   23
2   Jack   21
3   Rose   35
4   Alex   45
5  David   48

In [46]:
data

    Name  Age       City
0   John   32   Istanbul
1  Alice   23      Paris
2   Jack   21     London
3   Rose   35     Madrid
4   Alex   45  Sao Paulo
5  David   48      Miami

In [48]:
data[:3]

    Name  Age      City
0   John   32  Istanbul
1  Alice   23     Paris
2   Jack   21    London

In [ ]:
data["Name"] # a series

0     John
1    Alice
2     Jack
3     Rose
4     Alex
5    David
Name: Name, dtype: object

In [50]:
data[["Name"]] # a dataFrame

    Name
0   John
1  Alice
2   Jack
3   Rose
4   Alex
5  David

In [51]:
type(data[["Name"]])

pandas.core.frame.DataFrame

In [52]:
type(data["Name"])

pandas.core.series.Series

In [53]:
data

    Name  Age       City
0   John   32   Istanbul
1  Alice   23      Paris
2   Jack   21     London
3   Rose   35     Madrid
4   Alex   45  Sao Paulo
5  David   48      Miami

In [55]:
data[:3][["Name", "City"]]

    Name      City
0   John  Istanbul
1  Alice     Paris
2   Jack    London

In [57]:
# change the direction
data[["Name", "City"]][:3]

    Name      City
0   John  Istanbul
1  Alice     Paris
2   Jack    London

In [58]:
data

    Name  Age       City
0   John   32   Istanbul
1  Alice   23      Paris
2   Jack   21     London
3   Rose   35     Madrid
4   Alex   45  Sao Paulo
5  David   48      Miami

In [59]:
data.shape

(6, 3)

In [60]:
data.dtypes

Name    object
Age      int64
City    object
dtype: object

In [61]:
data

    Name  Age       City
0   John   32   Istanbul
1  Alice   23      Paris
2   Jack   21     London
3   Rose   35     Madrid
4   Alex   45  Sao Paulo
5  David   48      Miami

In [62]:
data.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [63]:
data.index

RangeIndex(start=0, stop=6, step=1)

In [64]:
data

    Name  Age       City
0   John   32   Istanbul
1  Alice   23      Paris
2   Jack   21     London
3   Rose   35     Madrid
4   Alex   45  Sao Paulo
5  David   48      Miami

In [65]:
data["debt"] = 25
data

    Name  Age       City  debt
0   John   32   Istanbul    25
1  Alice   23      Paris    25
2   Jack   21     London    25
3   Rose   35     Madrid    25
4   Alex   45  Sao Paulo    25
5  David   48      Miami    25

In [66]:
data["debt2"] = [20, 21, 19, 26, 22, 18]
data

    Name  Age       City  debt  debt2
0   John   32   Istanbul    25     20
1  Alice   23      Paris    25     21
2   Jack   21     London    25     19
3   Rose   35     Madrid    25     26
4   Alex   45  Sao Paulo    25     22
5  David   48      Miami    25     18

In [67]:
data["debt2"] = [22, 19, 19, 100, 22, 18]
data

    Name  Age       City  debt  debt2
0   John   32   Istanbul    25     22
1  Alice   23      Paris    25     19
2   Jack   21     London    25     19
3   Rose   35     Madrid    25    100
4   Alex   45  Sao Paulo    25     22
5  David   48      Miami    25     18

In [68]:
data

    Name  Age       City  debt  debt2
0   John   32   Istanbul    25     22
1  Alice   23      Paris    25     19
2   Jack   21     London    25     19
3   Rose   35     Madrid    25    100
4   Alex   45  Sao Paulo    25     22
5  David   48      Miami    25     18

In [69]:
data.drop("debt", axis=1)

    Name  Age       City  debt2
0   John   32   Istanbul     22
1  Alice   23      Paris     19
2   Jack   21     London     19
3   Rose   35     Madrid    100
4   Alex   45  Sao Paulo     22
5  David   48      Miami     18

In [71]:
#data = data.drop("debt", axis=1)
data.drop("debt", axis=1, inplace=True)
data

    Name  Age       City  debt2
0   John   32   Istanbul     22
1  Alice   23      Paris     19
2   Jack   21     London     19
3   Rose   35     Madrid    100
4   Alex   45  Sao Paulo     22
5  David   48      Miami     18

In [72]:
data.drop(["debt2", "City"], axis=1, inplace=True)
data

    Name  Age
0   John   32
1  Alice   23
2   Jack   21
3   Rose   35
4   Alex   45
5  David   48

In [73]:
data.drop(1, axis=0, inplace=True)
data

    Name  Age
0   John   32
2   Jack   21
3   Rose   35
4   Alex   45
5  David   48

In [74]:
data.drop([2,3], axis=0, inplace=True)
data

    Name  Age
0   John   32
4   Alex   45
5  David   48

In [75]:
data[:2]

   Name  Age
0  John   32
4  Alex   45

In [77]:
pd.Series([True, False]).dtypes

dtype('bool')